# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'quec_blekit_ios_Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for quec_blekit_ios_Sample

  target 'quec_blekit_ios_SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'quec_blekit_ios_SampleUITests' do
    # Pods for testing
  end

end
